---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: wordpress-app
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress-app
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube_fs/backend"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress-app
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: wordpress-app
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      #dnsPolicy: "None"
      #dnsConfig:
      #  nameservers:
      #    - 10.233.0.3
      #    - 8.8.8.8
      #  searches:
      #    - default.svc.cluster.local
      #    - svc.cluster.local
      #    - cluster.local
      #    - cbr1.vault
      volumes: 
        - name: mysql-pv-storage
          persistentVolumeClaim:
             claimName: mysql-pv-claim
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pv-storage
          mountPath: "/var/lib/mysql"
