---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-app
---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress-app
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress-app
  name: wp-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube_fs/frontend"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress-app
  name: wp-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: wordpress-app
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      #dnsPolicy: "None"
      #dnsConfig:
      #  nameservers:
      #    - 10.233.0.3
      #    - 8.8.8.8
      #  searches:
      #    - default.svc.cluster.local
      #    - svc.cluster.local
      #    - cluster.local
      #    - cbr1.vault
      #restartPolicy: Always
      volumes:
        - name: wp-pv-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wp-pv-storage
          mountPath: "/var/www/html"
